sudo: required
dist: trusty
# use minimal image:
language: generic
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:paparazzi-uav/ppa -y
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -q
install:
  - sudo apt-get install paparazzi-dev paparazzi-jsbsim gcc-arm-none-eabi libipc-run-perl
script:
  - make test

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "QGE7s/sTIX3F4hG8YYbpYjB2x0YsUUo9qHf+Dv5BqNcTtZ2TLO0tHPWxoI5wlRLiMEOOnINNwYk7ooM3oOXa0Fm9urja9k78cFutbbDtvGD6DjUFajwJ0KnwXnLulCgG+l67umGitSazQpyEQE4pvX/8EnB9/pgq706DlmCbkds="

addons:
  coverity_scan:
    project:
      name: "paparazzi/paparazzi"
      description: "Build submitted via Travis CI"
    notification_email: paparazzi-builds@nongnu.org
    build_command_prepend: "make ext"
    build_command: "make"
    branch_pattern: coverity_scan

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4187f8dda7a22a92b749
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
